$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: churn-sklearn-env
description: Environment for churn model training and inference.
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
conda_file: conda.yml
